language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hubot-script-gulp' ]; then cd .. && eval "mv $currentfolder generator-hubot-script-gulp" && cd generator-hubot-script-gulp; fi
after_script:
  - npm run coveralls
